version: '3.8'

volumes:
  api-logs:
    external: true

services:
  api-service:
    image: api:1.0
    ports:
      - "7070:7070"
    volumes:
      - type: volume
        source: api-logs
        target: /project/api-logs