version: '3.8'

volumes:
  api-logs:
    external: true

services:
  api-service:
    image: api:1.0
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: api-logs
        target: /api/api-logs