filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
    fields:
      log_type: api_log
    json.keys_under_root: true
    json.overwrite_keys: true

output.logstash:
  hosts: [ 'logstash:5044' ]