http.host: "0.0.0.0"

monitoring.elasticsearch.hosts: [ 'http://elasticsearch:9200/' ]
monitoring.elasticsearch.username: '{your logstash id}'
monitoring.elasticsearch.password: '{your logstash password}'