version: '3.8'

networks:
  monitoring_network:
    external: true

volumes:
  api-logs:
    external: true

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.8.2
    volumes:
      - type: bind
        source: ./filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: volume
        source: api-logs
        target: /usr/share/filebeat/logs
    command: filebeat -e
    networks:
      - monitoring_network