version: '3.8'

networks:
  monitoring_network:
    external: true

volumes:
  kafka-broker-01-data:
  kafka-broker-02-data:
  kafka-broker-03-data:
  kafka-controller-01-data:
  kafka-controller-02-data:
  kafka-controller-03-data:

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8080:8080'
    depends_on:
      - kafka-broker-01
      - kafka-broker-02
      - kafka-broker-03
    environment:
      - KAFKA_CLUSTERS_0_NAME=Local-Kraft-Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker-01:9092, kafka-broker-02:9093, kafka-broker-03:9094
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED=true
    networks:
      - monitoring_network

  kafka-broker-01:
    image: confluentinc/cp-kafka:7.4.3
    ports:
      - "9092:9092"
    user: root
    environment:
      CLUSTER_ID: ckjPoprWQzOf0-FuNkGfFQ
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: BROKER://kafka-broker-01:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-broker-01:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@kafka-controller-01:19092,5@kafka-controller-02:29092,6@kafka-controller-03:39092
      KAFKA_LOG_DIRS: /tmp/kafka-broker-logs
    volumes:
      - kafka-broker-01-data:/tmp/kafka-broker-logs
    networks:
      - monitoring_network

  kafka-broker-02:
    image: confluentinc/cp-kafka:7.4.3
    ports:
      - "9093:9093"
    user: root
    environment:
      CLUSTER_ID: ckjPoprWQzOf0-FuNkGfFQ
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: BROKER://kafka-broker-02:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-broker-02:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@kafka-controller-01:19092,5@kafka-controller-02:29092,6@kafka-controller-03:39092
      KAFKA_LOG_DIRS: /tmp/kafka-broker-logs
    volumes:
      - kafka-broker-02-data:/tmp/kafka-broker-logs
    networks:
      - monitoring_network

  kafka-broker-03:
    image: confluentinc/cp-kafka:7.4.3
    ports:
      - "9094:9094"
    user: root
    environment:
      CLUSTER_ID: ckjPoprWQzOf0-FuNkGfFQ
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: BROKER://kafka-broker-03:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-broker-03:9094
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@kafka-controller-01:19092,5@kafka-controller-02:29092,6@kafka-controller-03:39092
      KAFKA_LOG_DIRS: /tmp/kafka-broker-logs
    volumes:
      - kafka-broker-03-data:/tmp/kafka-broker-logs
    networks:
      - monitoring_network

  kafka-controller-01:
    image: confluentinc/cp-kafka:7.4.3
    ports:
      - "19092:19092"
    user: root
    environment:
      CLUSTER_ID: ckjPoprWQzOf0-FuNkGfFQ
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 4
      KAFKA_LISTENERS: CONTROLLER://kafka-controller-01:19092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@kafka-controller-01:19092,5@kafka-controller-02:29092,6@kafka-controller-03:39092
      KAFKA_LOG_DIRS: /tmp/kafka-controller-logs
    volumes:
      - kafka-controller-01-data:/tmp/kafka-controller-logs
    networks:
      - monitoring_network

  kafka-controller-02:
    image: confluentinc/cp-kafka:7.4.3
    ports:
      - "29092:29092"
    user: root
    environment:
      CLUSTER_ID: ckjPoprWQzOf0-FuNkGfFQ
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 5
      KAFKA_LISTENERS: CONTROLLER://kafka-controller-02:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@kafka-controller-01:19092,5@kafka-controller-02:29092,6@kafka-controller-03:39092
      KAFKA_LOG_DIRS: /tmp/kafka-controller-logs
    volumes:
      - kafka-controller-02-data:/tmp/kafka-controller-logs
    networks:
      - monitoring_network

  kafka-controller-03:
    image: confluentinc/cp-kafka:7.4.3
    ports:
      - "39092:39092"
    user: root
    environment:
      CLUSTER_ID: ckjPoprWQzOf0-FuNkGfFQ
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 6
      KAFKA_LISTENERS: CONTROLLER://kafka-controller-03:39092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 4@kafka-controller-01:19092,5@kafka-controller-02:29092,6@kafka-controller-03:39092
      KAFKA_LOG_DIRS: /tmp/kafka-controller-logs
    volumes:
      - kafka-controller-03-data:/tmp/kafka-controller-logs
    networks:
      - monitoring_network